project_id = "tvqmhdpcixkfsudxughs"

[functions.analyze-patterns]
verify_jwt = false

[functions.fetch-pv-forecast]
verify_jwt = false

[functions.tuya-control]
verify_jwt = false

[functions.pv-automation]
verify_jwt = false

[functions.aggregate-energy-data]
verify_jwt = false

[functions.apply-recommendations]
verify_jwt = false

[functions.calculate-heating-power]
verify_jwt = false
