-- RLS für alle Tabellen deaktivieren
ALTER TABLE rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE room_recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE heating_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE heating_recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE energy_readings DISABLE ROW LEVEL SECURITY;
ALTER TABLE hourly_aggregates DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_patterns DISABLE ROW LEVEL SECURITY;
ALTER TABLE detected_patterns DISABLE ROW LEVEL SECURITY;
ALTER TABLE pv_forecasts DISABLE ROW LEVEL SECURITY;
ALTER TABLE smartfox_settings DISABLE ROW LEVEL SECURITY;